import { createHash } from "node:crypto";
import { lstat, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { spawnSync } from "node:child_process";
import path from "node:path";
const SUBJECT="subject",CONTROLLER=".devex-controller",MANIFEST_PATH=SUBJECT+"/.devex/oss-verification/manifest.json",WORKFLOW_PATH=".github/workflows/devex-oss-verification.yml",RUNNER_PATH=".devex/oss-verification/run.mjs",RESULT_PATH=SUBJECT+"/.devex/oss-verification/result.json";
const D=/^sha256:[a-f0-9]{64}$/,S=/^[a-f0-9]{40}$/;const fail=(m)=>{throw new Error(m)},exact=(v,k)=>{const a=Object.keys(v).sort(),b=[...k].sort();if(a.length!==b.length||a.some((x,i)=>x!==b[i]))fail("closed manifest violation")};
const canonical=(v)=>v===null?"null":typeof v==="string"||typeof v==="boolean"?JSON.stringify(v):typeof v==="number"&&Number.isFinite(v)?JSON.stringify(Object.is(v,-0)?0:v):Array.isArray(v)?"["+v.map(canonical).join(",")+"]":v&&typeof v==="object"?"{"+Object.keys(v).sort().map(k=>JSON.stringify(k)+":"+canonical(v[k])).join(",")+"}":fail("non-canonical value");
const cd=(v)=>"sha256:"+createHash("sha256").update(canonical(v)).digest("hex"),raw=(v)=>"sha256:"+createHash("sha256").update(v).digest("hex"),blob=(v)=>createHash("sha1").update("blob "+v.byteLength+"\0").update(v).digest("hex");
const manifest=JSON.parse(await readFile(MANIFEST_PATH,"utf8"));exact(manifest,["apiVersion","assuranceDefaultRef","assuranceRepositoryRef","authorizationDigest","baseGitSha","baseRevisionDigest","bootstrapReceiptDigest","bundleVersion","candidateControlEvidence","controllerRevisionSha","expectedFailureFingerprintDigest","headRepositoryRef","kind","manifestDigest","oracleArtifactDigest","oracleDigest","oraclePaths","profile","repositoryRef","requiredChecksDigest","resultArtifactName","resultPath","revisionDigest","runId","runnerBlobSha","runnerDigest","runnerPath","stage","testIdentityDigest","verificationPlan","workflowBlobSha","workflowDigest","workflowPath"]);const{manifestDigest,...mc}=manifest;
if(manifestDigest!==process.env.DEVEX_EXPECTED_MANIFEST_DIGEST||manifestDigest!==cd({contract:"devex-oss-github-verification-manifest/v3",...mc})||manifest.runId!==process.env.DEVEX_EXPECTED_RUN_ID||manifest.stage!==process.env.DEVEX_EXPECTED_STAGE)fail("dispatch manifest drift");
if(manifest.apiVersion!=="devex-oss-github-verification-manifest/v3"||manifest.bundleVersion!=="3.0.0"||manifest.repositoryRef!=="github:addyosmani/clarity"||manifest.headRepositoryRef!=="github:vmaliwal/clarity"||manifest.assuranceRepositoryRef!=="github:vmaliwal/clarity")fail("manifest identity drift");
for(const k of ["baseRevisionDigest","revisionDigest","oracleDigest","oracleArtifactDigest","testIdentityDigest","expectedFailureFingerprintDigest","authorizationDigest","requiredChecksDigest","workflowDigest","runnerDigest","bootstrapReceiptDigest"])if(!D.test(manifest[k]))fail("manifest digest invalid");
for(const[p,d,b]of[[CONTROLLER+"/"+WORKFLOW_PATH,manifest.workflowDigest,manifest.workflowBlobSha],[CONTROLLER+"/"+RUNNER_PATH,manifest.runnerDigest,manifest.runnerBlobSha]]){const x=await readFile(p);if(raw(x)!==d||blob(x)!==b)fail("controller blob drift")}
if(process.env.GITHUB_REPOSITORY!=="vmaliwal/clarity"||process.env.GITHUB_EVENT_NAME!=="workflow_dispatch"||process.env.GITHUB_SHA!==manifest.controllerRevisionSha)fail("assurance source drift");
const providerSha=process.env.DEVEX_EXPECTED_TARGET_SHA;if(!S.test(providerSha))fail("target sha invalid");const co=spawnSync("git",["-C",SUBJECT,"rev-parse","HEAD"],{encoding:"utf8"});if(co.status!==0||co.stdout.trim()!==providerSha)fail("target checkout drift");
for(const p of manifest.oraclePaths){if(!/^site\/tests\/site\/[A-Za-z0-9][A-Za-z0-9._-]{0,180}\.test\.mjs$/.test(p))fail("oracle path invalid");const st=await lstat(SUBJECT+"/"+p);if(!st.isFile()||st.isSymbolicLink())fail("oracle unavailable")}
const token=process.env.DEVEX_GITHUB_TOKEN;if(!token)fail("token unavailable");const headers={Accept:"application/vnd.github+json",Authorization:"Bearer "+token,"X-GitHub-Api-Version":"2022-11-28"};
const pullNumber=Number(process.env.DEVEX_EXPECTED_PULL_REQUEST_NUMBER);if(!Number.isSafeInteger(pullNumber)||pullNumber<1)fail("pull request number invalid");const prr=await fetch("https://api.github.com/repos/addyosmani/clarity/pulls/"+pullNumber,{headers});if(!prr.ok)fail("pull request unavailable");const pr=await prr.json();if(pr.number!==pullNumber||pr.head?.sha!==providerSha||pr.head?.repo?.full_name!=="vmaliwal/clarity"||pr.base?.sha!==manifest.baseGitSha)fail("pull request source drift");
const wr=await fetch("https://api.github.com/repos/vmaliwal/clarity/actions/workflows/"+encodeURIComponent(WORKFLOW_PATH),{headers});if(!wr.ok)fail("workflow unavailable");const wf=await wr.json();if(!Number.isSafeInteger(wf.id)||wf.path!==WORKFLOW_PATH||wf.state!=="active")fail("workflow identity drift");
const wref=process.env.GITHUB_WORKFLOW_REF??"",marker="vmaliwal/clarity/"+WORKFLOW_PATH+"@";if(!wref.startsWith(marker))fail("workflow ref unavailable");const sourceRef=wref.slice(marker.length);
const plan=manifest.verificationPlan,commands={"node-npm/v1":{install:["npm","ci","--ignore-scripts","--no-audit","--no-fund"],test:["npm","test"]},"python-uv/v1":{install:["uv","sync","--frozen"],test:["uv","run","--offline","pytest"]},"go-mod/v1":{install:["go","mod","download"],test:["go","test","./..."]},"rust-cargo/v1":{install:["cargo","fetch","--locked"],test:["cargo","test","--locked","--offline"]},"jvm-gradle-lock/v1":{install:["gradle","--no-daemon","dependencies"],test:["gradle","--offline","--no-daemon","test"]}};
exact(plan,["apiVersion","baseGitSha","controlPaths","controlSetDigest","dependencyInstall","imageDigest","imageRef","kind","lockfileDigest","lockfilePath","markerDigest","markerPath","profile","profileDigest","repositoryRef","test","workdir"]);const expected=commands[plan.profile];if(!expected||manifest.profile!==plan.profile||plan.repositoryRef!==manifest.repositoryRef||plan.baseGitSha!==manifest.baseGitSha||plan.imageRef.slice(plan.imageRef.lastIndexOf("@")+1)!==plan.imageDigest||!/^.+@sha256:[a-f0-9]{64}$/.test(plan.imageRef))fail("profile authority drift");
for(const[name,phase,argv,network]of[["install",plan.dependencyInstall,expected.install,"bridge"],["test",plan.test,expected.test,"none"]]){exact(phase,["argv","commandDigest","credentialsInjected","cwd","network","shell"]);if(JSON.stringify(phase.argv)!==JSON.stringify(argv)||phase.cwd!==plan.workdir||phase.network!==network||phase.credentialsInjected!==false||phase.shell!==false||phase.commandDigest!==cd({contract:"controller-verification-command/v1",argv:[...argv],cwd:plan.workdir,network,credentialsInjected:false,shell:false}))fail(name+" command drift")}
const{profileDigest,...pc}=plan;if(profileDigest!==cd({contract:"controller-verification-execution-plan/v1",...pc}))fail("profile digest drift");if(manifest.stage==="baseline"?manifest.candidateControlEvidence!==null:manifest.candidateControlEvidence===null)fail("candidate evidence stage drift");if(manifest.candidateControlEvidence){const ev=manifest.candidateControlEvidence,{evidenceDigest,...ec}=ev;if(ev.profileDigest!==plan.profileDigest||ev.candidateRevisionDigest!==manifest.revisionDigest||evidenceDigest!==cd({contract:"controller-verification-candidate-controls/v1",...ec}))fail("candidate evidence drift")}
const uid=process.getuid?.(),gid=process.getgid?.(),runnerTemp=process.env.RUNNER_TEMP;if(!Number.isSafeInteger(uid)||!Number.isSafeInteger(gid)||uid<=0||gid<=0||!runnerTemp||!path.isAbsolute(runnerTemp)||runnerTemp.includes(",")||/[\r\n\0]/.test(runnerTemp))fail("runner isolation identity unavailable");
const cacheRoot=await mkdtemp(path.join(runnerTemp,"devex-verification-cache-"));if(cacheRoot.includes(",")||/[\r\n\0]/.test(cacheRoot))fail("cache path invalid");
const cacheEnv={"node-npm/v1":["HOME=/tmp","NPM_CONFIG_CACHE=/devex-cache/npm"],"python-uv/v1":["HOME=/tmp","UV_CACHE_DIR=/devex-cache/uv","UV_PYTHON_DOWNLOADS=never"],"go-mod/v1":["HOME=/tmp","GOMODCACHE=/devex-cache/go-mod","GOCACHE=/devex-cache/go-build","GOPATH=/devex-cache/go-path"],"rust-cargo/v1":["HOME=/tmp","CARGO_HOME=/devex-cache/cargo","CARGO_TARGET_DIR=/devex-cache/cargo-target"],"jvm-gradle-lock/v1":["HOME=/tmp","GRADLE_USER_HOME=/devex-cache/gradle"]}[plan.profile];if(!cacheEnv)fail("cache policy unavailable");
const work=process.cwd()+"/"+SUBJECT,runPhase=(phase)=>spawnSync("docker",["run","--rm","--network",phase.network,"--read-only","--cap-drop","ALL","--security-opt","no-new-privileges:true","--pids-limit","256","--memory","4g","--cpus","2","--user",uid+":"+gid,"--tmpfs","/tmp:rw,noexec,nosuid,nodev,size=256m","--mount","type=bind,src="+work+",dst=/workspace","--mount","type=bind,src="+cacheRoot+",dst=/devex-cache","--workdir","/workspace/"+phase.cwd,"--env","CI=true",...cacheEnv.flatMap(v=>["--env",v]),plan.imageRef,...phase.argv],{stdio:"inherit",shell:false,env:{PATH:process.env.PATH??"/usr/local/bin:/usr/bin:/bin"}});let install,tested;try{install=runPhase(plan.dependencyInstall);if(install.status!==0)fail("install failed");tested=runPhase(plan.test)}finally{await rm(cacheRoot,{recursive:true,force:true})}const conclusion=tested.status===0?"success":"failure";
const rid=process.env.GITHUB_RUN_ID,attempt=Number(process.env.GITHUB_RUN_ATTEMPT);if(!rid||!Number.isSafeInteger(attempt)||attempt<1)fail("run identity invalid");const identity=cd({contract:"devex-github-workflow-execution-identity/v1",repositoryRef:manifest.repositoryRef,workflowRunId:rid,runAttempt:attempt,providerSha,event:"workflow_dispatch",workflowId:String(wf.id),workflowPath:WORKFLOW_PATH,workflowSourceRef:sourceRef,workflowSourceSha:manifest.controllerRevisionSha,workflowBlobSha:manifest.workflowBlobSha,workflowDigest:manifest.workflowDigest,referencedWorkflows:[]});
const result={apiVersion:"platform.devex/v1",kind:"OssProviderOracleResult",stage:manifest.stage,repositoryRef:manifest.repositoryRef,changeRequestRef:manifest.repositoryRef+":pull/"+pullNumber,baseRevisionDigest:manifest.baseRevisionDigest,baseGitSha:manifest.baseGitSha,providerSha,revisionDigest:manifest.revisionDigest,workflowRunId:rid,runAttempt:attempt,workflowRunHeadSha:manifest.controllerRevisionSha,workflowId:String(wf.id),workflowPath:WORKFLOW_PATH,workflowSourceRef:sourceRef,workflowSourceSha:manifest.controllerRevisionSha,workflowBlobSha:manifest.workflowBlobSha,workflowExecutionIdentityDigest:identity,workflowRef:manifest.assuranceRepositoryRef+":"+WORKFLOW_PATH+"@blob:"+manifest.workflowBlobSha,workflowDigest:manifest.workflowDigest,requiredChecksDigest:manifest.requiredChecksDigest,authorizationDigest:manifest.authorizationDigest,oracleDigest:manifest.oracleDigest,testIdentityDigest:manifest.testIdentityDigest,status:"completed",conclusion,failureFingerprintDigest:conclusion==="failure"?manifest.expectedFailureFingerprintDigest:null,completedAt:new Date().toISOString()};exact(result,["apiVersion","authorizationDigest","baseGitSha","baseRevisionDigest","changeRequestRef","completedAt","conclusion","failureFingerprintDigest","kind","oracleDigest","providerSha","repositoryRef","requiredChecksDigest","revisionDigest","runAttempt","stage","status","testIdentityDigest","workflowBlobSha","workflowDigest","workflowExecutionIdentityDigest","workflowId","workflowPath","workflowRef","workflowRunHeadSha","workflowRunId","workflowSourceRef","workflowSourceSha"]);await writeFile(RESULT_PATH,JSON.stringify(result)+"\n",{mode:0o600,flag:"wx"});if(manifest.stage==="baseline"||conclusion!=="success")process.exitCode=1;
